#!/bin/sh

set -e
set -x

function cs() {
    rm -rf build
    mkdir build
    cd build
    cmake .. -G Ninja
}

function br() {
    cd build
    cmake --build .
    ./geometry_crash
}

case "$1" in
	"setup")
		cs
		;;
	"run")
		br
		;;
	*)
	echo "Invaled Command"
	;;
esac
